title: Geek and Chef
description: Personal blog，非典型程序员
show_downloads: true
google_analytics: 'UA-157135686-1'
theme: geek-and-chef

timezone: Asia/Shanghai
encoding: utf-8

plugins:
  - jekyll-seo-tag