# 站点主题配置
theme       : jekyll-theme-cayman
# Site 配置
locale      : "en-US"
#站点名，站点左上角
title       : "Geek and Chef"
# 站点副标题
description : "非典型程序员"
# name
name        : "舟自横"
# author 相关
author      : 
  name      : "舟自横"
# email: #你的联系邮箱
# language: zh-CN #中国人嘛，用中文

# URL #这项暂不配置，绑定域名后，欲创建sitemap.xml需要配置该项
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://zipperary.com
root: /
# permalink: :year/:month/:day/:title/
# tag_dir: tags
# archive_dir: archives
# category_dir: categories

# Writing 文章布局、写作格式的定义，不修改
#new_post_name: :title.md # File name of new posts
#default_layout: post
#auto_spacing: false # Add spaces between asian characters and western characters
#titlecase: false # Transform title into titlecase
#max_open_file: 100
#filename_case: 0
#highlight:
  #enable: true
  #backtick_code_block: true
  #line_number: true
  #tab_replace:

# Category & Tag
# default_category: uncategorized
# category_map:
# tag_map:

# Archives 默认值为2，这里都修改为1，相应页面就只会列出标题，而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
# archive: 1
# category: 1
# tag: 1
